function WriteCaseFile(handles)
%%  Write case file
fid_cas = fopen(['../case_files/' get(handles.name,'String') '.cas'],'wt');
fname = [get(handles.name,'String') '.neu'];
CaseData = struct([]);
CaseData = AddVal2Case(CaseData,'INPUT',fname,'string');
CaseData = AddVal2Case(CaseData,'PMAX',MaxP,'int');
CaseData = AddVal2Case(CaseData,'SCALE',Scale,'double');
CaseData = AddVal2Case(CaseData,'BODYNUM',numbodies,'int');
CaseData = AddVal2Case(CaseData,'ATTITUDES', Attitudes,'double');
CaseData = AddVal2Case(CaseData,'CGBODIES',Origin, 'double');
CaseData = AddVal2Case(CaseData,'RATEBODIES',Rates,'double');
CaseData = AddVal2Case(CaseData,'VELBODIES',Vels,'double');
CaseData = AddVal2Case(CaseData,'NAME',name,'string');


fprintf(fid_cas,'#          Input file generated by MATLAB Version:  %s\n', version);
fprintf(fid_cas,'#          %s\n', datestr(now));


for i = 1:CaseData.NumVals
    fprintf(fid_cas,'%s:\t%s;\n',CaseData.Data{i}.Name, CaseData.Data{i}.Val);
end

fclose(fid_cas);

system(['cat ' dir2 name '.cas']);