function [figure1 p] = createfigure(VertexNormals1, ZData1, YData1, XData1, Vertices1, Faces1,test)
%CREATEFIGURE(VERTEXNORMALS1,ZDATA1,YDATA1,XDATA1,VERTICES1,FACES1)
%  VERTEXNORMALS1:  patch vertexnormals
%  ZDATA1:  patch zdata
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces

%  Auto-generated by MATLAB on 09-Oct-2009 18:21:29
if test
fullscreen = get(0,'ScreenSize');

% Create figure
figure1 = figure('Position',[0 -50 (0.5*0.75)*fullscreen(3) .75*fullscreen(4)],'XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)',...
    'Renderer','OpenGL',...
    'PaperSize',[20.98 29.68],'Color',[1.0 1.0 1.0],'DoubleBuffer','on');

% Create axes
axes1 = axes('Parent',figure1,'DataAspectRatio',[1 1 1],...
    'CameraTarget',[18.92 0.3975 3.921],...
    'CameraPosition',[-267.8 -372.6 275.3]);
else
    figure1 = gcf;
    axes1 = gca;
end
% Create patch
p = patch('Parent',axes1,'FaceLighting','phong',...
    'ZData',ZData1,...
    'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'Faces',Faces1,...
    'FaceColor',[0.702 0.7804 1],...
    'EdgeColor','none');

% Create light
%light('Parent',axes1,'Position',[20 0 173.2]);

drawnow