#!/bin/sh
#PBS -l nodes=1:ppn=4
#PBS -m bea
#PBS -M tom.mccombes@strath.ac.uk

cd $PBS_O_WORKDIR
nprocs=`wc -l $PBS_NODEFILE | awk '{ print $1 }'`
/home/lap05140/./main 2vertical_axis.cas > dump_2vertical_axis
